# This is a TOML document. Boom.

version = "0.1.0"

addr = "0.0.0.0:6205"
authType = 1

[clusters]
[clusters.cluster1]
cluster = "cluster1"
brokers = ["59.110.27.156:8922"]
sync = false

[log]
dir = "/data/log/databus"

[httpServer]
addr = "0.0.0.0:6206"
timeout = "1s"

[redis]
addr="59.110.27.156:6379"
password="testwashcar"
dB=1
dialTimeout="3s"
readTimeout="5s"
writeTimeout="3s"
idleTimeout ="30s"
idleCheckFrequency="15s"
poolTimeout="30s"
maxConnAge="30s"
minIdleConns=5
poolSize=20

[mysql]
addr = "59.110.27.156:3306"
dsn = "testuser:test123@tcp(59.110.27.156:3306)/washcar_db?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 2
idle = 1
idleTimeout ="4h"
queryTimeout = "150ms"
execTimeout = "100ms"
tranTimeout = "200ms"
[mysql.breaker]
window = "3s"
sleep = "100ms"
bucket = 10
ratio = 0.5
request = 100
